apiVersion: apps/v1
kind: Deployment
metadata:
  name: phive-doc-validator
  labels:
    app: phive-doc-validator
spec:
  replicas: 2
  selector:
    matchLabels:
      app: phive-doc-validator
  template:
    metadata:
      labels:
        app: phive-doc-validator
    spec:
      containers:
        - name: phive-doc-validator
          image: eaglessoftbv/phive-doc-validator:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: CONTEXT_PATH
              value: "/"
            - name: LOG_FORMAT
              value: "json"
            - name: LOG_LEVEL
              value: "WARN"
          readinessProbe:
            httpGet:
              path: /api
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /api
              port: http
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 3
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: phive-doc-validator
  labels:
    app: phive-doc-validator
spec:
  type: ClusterIP
  selector:
    app: phive-doc-validator
  ports:
    - name: http
      port: 80
      targetPort: http
