#!/bin/sh
set -eu

CATALINA_CONF_DIR="/usr/local/tomcat/conf/Catalina/localhost"
DOC_BASE="/opt/app"
LOGBACK_JSON_CONFIG="/opt/app/WEB-INF/classes/logback-json.xml"
LOGBACK_PLAIN_CONFIG="/opt/app/WEB-INF/classes/logback-plain.xml"

mkdir -p "${CATALINA_CONF_DIR}"

# Remove previously generated context descriptors.
for f in "${CATALINA_CONF_DIR}"/*.xml; do
  [ -e "$f" ] || continue
  if grep -q "Generated by phive-validation-api container" "$f"; then
    rm -f "$f"
  fi
done

RAW_CONTEXT_PATH="${CONTEXT_PATH:-/}"
NORMALIZED_CONTEXT="$(printf '%s' "${RAW_CONTEXT_PATH}" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')"

if [ -z "${NORMALIZED_CONTEXT}" ] || [ "${NORMALIZED_CONTEXT}" = "/" ]; then
  CONTEXT_FILE="ROOT.xml"
else
  NORMALIZED_CONTEXT="$(printf '%s' "${NORMALIZED_CONTEXT}" | sed -e 's#^/*##' -e 's#/*$##')"
  CONTEXT_FILE="$(printf '%s' "${NORMALIZED_CONTEXT}" | tr '/' '#').xml"
fi

cat > "${CATALINA_CONF_DIR}/${CONTEXT_FILE}" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by phive-validation-api container -->
<Context docBase="${DOC_BASE}" />
EOF

# Configure logging format for container output.
# Defaults to JSON, can be overridden with LOG_FORMAT=plain or LOGBACK_CONFIG_FILE.
if [ -n "${LOGBACK_CONFIG_FILE:-}" ]; then
  SELECTED_LOGBACK_CONFIG="${LOGBACK_CONFIG_FILE}"
else
  case "$(printf '%s' "${LOG_FORMAT:-json}" | tr '[:upper:]' '[:lower:]')" in
    plain)
      SELECTED_LOGBACK_CONFIG="${LOGBACK_PLAIN_CONFIG}"
      ;;
    json|*)
      SELECTED_LOGBACK_CONFIG="${LOGBACK_JSON_CONFIG}"
      ;;
  esac
fi

if [ -n "${CATALINA_OPTS:-}" ]; then
  export CATALINA_OPTS="${CATALINA_OPTS} -Dlogback.configurationFile=${SELECTED_LOGBACK_CONFIG}"
else
  export CATALINA_OPTS="-Dlogback.configurationFile=${SELECTED_LOGBACK_CONFIG}"
fi

exec "$@"
